spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/simuladordb}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET}
  access-token-ttl: ${JWT_ACCESS_TTL:900000}
  refresh-token-ttl: ${JWT_REFRESH_TTL:2592000000}

